# Generated by Django 2.0.2 on 2018-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('siret', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('last_iegh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('year', models.PositiveIntegerField(null=True)),
                ('direction_male', models.PositiveIntegerField(null=True)),
                ('direction_female', models.PositiveIntegerField(null=True)),
                ('global_male_ratio', models.FloatField()),
                ('employees_count', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='data',
            field=models.ManyToManyField(to='api.OrganizationData'),
        ),
    ]
