# Generated by Django 2.0.2 on 2018-03-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180303_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='data',
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
    ]
