# Generated by Django 2.0.2 on 2018-03-04 10:43

from django.db import migrations, models
import math

def set_iehg(apps, schema_editor):
    OData = apps.get_model('api', 'OrganizationData')
    for data in OData.objects.all().iterator():
        get_direction_female_ratio = data.direction_female / (data.direction_female + data.direction_male)
        data.iehg = 100 * (1 - math.sqrt(math.fabs(1 - data.global_male_ratio / 100 - get_direction_female_ratio)))
        data.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180303_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='last_iegh',
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='iehg',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.RunPython(set_iehg),
        migrations.AlterField(
            model_name='organizationdata',
            name='employees_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
